### ISSUE TITLE
No instructions on how to use.

### ISSUE THREAD

**Issue by elcoso** [rafyco/ytrss#18]
Everything is good and fine... but how do we use this?

**Comment by rafyco** [comment]
I'll add proper informatorom to README file, but you can find instrucions in documentation https://ytrss.readthedocs.io/en/latest/modules.html#config-file-structure and wnen you invoke this instrucions after installation.

```
ytdown --help
```

**Comment by rafyco** [comment]
See https://ytrss.readthedocs.io/en/latest/
